### ISSUE TITLE
Reports & dashboards analyzer not working

### ISSUE THREAD

**Issue by fmimouna** [SalesforceLabs/OrgCheck#610]
**Describe the bug**
In the analytics tab when I run the report or dashboard subtabs, I got the error message bellow

**To Reproduce**

Run recipe "reports" An error occurred while running the dataset internal-active-users.
Run dataset "internal-active-users" There was an error during the process...
Context information about the issue:
Message: There was an error while running a SOQL query with the custom queryMore
SoqlQuery: SELECT UserId, LoginType, AuthMethodReference, Status, COUNT(Id) CntLogin FROM LoginHistory WHERE LoginType = 'Application' OR LoginType LIKE '%SSO%' GROUP BY UserId, LoginType, AuthMethodReference, Status
Tooling:
Field: LoginTime
Cause: 'Application' OR LoginType LIKE '%SSO%' AND LoginTime > 2025-09-09T20:14:09.000+0000 ^ ERROR at Row:1:Column:175 unexpected token: 'AND'
Where: SalesforceManagerImpl.soqlQuery/_customSOQLQuery

----------------------------------------------------------------------------------------------------------------

Run recipe "dashboards" An error occurred while running the dataset internal-active-users.
Run dataset "internal-active-users" There was an error during the process...
Context information about the issue:
Message: There was an error while running a SOQL query with the custom queryMore
SoqlQuery: SELECT UserId, LoginType, AuthMethodReference, Status, COUNT(Id) CntLogin FROM LoginHistory WHERE LoginType = 'Application' OR LoginType LIKE '%SSO%' GROUP BY UserId, LoginType, AuthMethodReference, Status
Tooling:
Field: LoginTime
Cause: 'Application' OR LoginType LIKE '%SSO%' AND LoginTime > 2025-09-09T20:14:09.000+0000 ^ ERROR at Row:1:Column:175 unexpected token: 'AND'
Where: SalesforceManagerImpl.soqlQuery/_customSOQLQuery

**Comment by VinceFINET** [comment]
7.3 deployed in orgs. And hopefully yours as well.

Check if you received the Org Check 7.3 in the "installed package" section in the setup menu.
If not can you upgrade from App Exchange

Then check if the issue is corrected.
if not reopen this ticket.

**Comment by fmimouna** [comment]
I checked my Org and I have the right version

Uninstall |   | Org Check | VinceFINET corporation | 7.3 | orgcheck | Free | N/A | N/A | N/A | N/A

**Comment by VinceFINET** [comment]
And you still have the issue?
Try to clean the app cache from the tab « cache management »

**Comment by fmimouna** [comment]
Yes @VinceFINET , I still have the same error

<img width="1034" height="396" alt="Image" src="https://github.com/user-attachments/assets/42d92487-5ea8-4f47-8470-1b2d9a4c7810" />

<img width="708" height="415" alt="Image" src="https://github.com/user-attachments/assets/5193ad6a-0e3b-4b0e-abaa-4cb825d2f2c0" />

**Comment by VinceFINET** [comment]
Ok I understood the error you have.
Sorry about that. I will have to patch this in 7.4 next week.
Thank you!

**Comment by VinceFINET** [comment]
Test : need to test the resulting soql when doing custom query more

> Message ID: ***@***.***>
>>
> Lead: the added AND statement is incompatible when initial where statement
contains OR. Addiction parenthesis might resolve the issue.

**Comment by VinceFINET** [comment]
When the app is using the custom query more, it generates dynamic queries.
one of them is buggy (the one you detected!).

Here is the list of all queries the app is performing with custom query more (i put some hardcoded values to make them runnable):

- SELECT ApexClassOrTriggerId, ApexTestClassId, MAX(CreatedDate) qmField  FROM ApexCodeCoverage WHERE ApexClassOrTriggerId IN ('000000000000000') AND ApexTestClass.ManageableState IN ('installedEditable', 'unmanaged') AND CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY ApexClassOrTriggerId, ApexTestClassId  ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT DurableId, QualifiedApiName, Description, IsIndexed FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = 'Opportunity__c' AND EntityDefinition.NamespacePrefix = 'orgcheck'  AND DurableId > '000000000000000000' ORDER BY DurableId LIMIT 2000
- SELECT DurableId, QualifiedApiName, Description, IsIndexed FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = 'Account'  AND DurableId > '000000000000000000' ORDER BY DurableId LIMIT 2000
- SELECT DurableId, NamespacePrefix, DeveloperName, QualifiedApiName, ExternalSharingModel, InternalSharingModel FROM EntityDefinition WHERE KeyPrefix <> null AND DeveloperName <> null AND (NOT(KeyPrefix IN ('00a', '017', '02c', '0D5', '1CE'))) AND (NOT(QualifiedApiName like '%_hd')) AND DurableId > '000000000000000000' ORDER BY DurableId LIMIT 2000
- SELECT EntityDefinitionId, COUNT(Id) NbCustomFields, MAX(CreatedDate) qmField  FROM CustomField WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY EntityDefinitionId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT EntityDefinitionId, COUNT(Id) NbPageLayouts, MAX(CreatedDate) qmField  FROM Layout WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY EntityDefinitionId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT EntityDefinitionId, COUNT(Id) NbRecordTypes, MAX(CreatedDate) qmField  FROM RecordType WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY EntityDefinitionId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT TableEnumOrId, COUNT(Id) NbWorkflowRules, MAX(CreatedDate) qmField  FROM WorkflowRule WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY TableEnumOrId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT EntityDefinitionId, COUNT(Id) NbValidationRules, MAX(CreatedDate) qmField  FROM ValidationRule WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY EntityDefinitionId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT EntityDefinitionId, COUNT(Id) NbTriggers, MAX(CreatedDate) qmField  FROM ApexTrigger WHERE CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY EntityDefinitionId ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT LayoutId, COUNT(ProfileId) CountAssignment, MAX(CreatedDate) qmField  FROM ProfileLayout WHERE Profile.Name != null AND CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY LayoutId  ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT Browser, COUNT(Id) CntBrowser, MAX(LoginTime) qmField  FROM LoginHistory WHERE LoginType = 'Application' AND LoginTime > 2024-12-22T09:09:05.626+01:00  GROUP BY Browser  ORDER BY MAX(LoginTime) LIMIT 2000
- SELECT UserId, LoginType, AuthMethodReference, Status, COUNT(Id) CntLogin, MAX(LoginTime) qmField  FROM LoginHistory WHERE LoginType = 'Application' OR LoginType LIKE '%SSO%' AND LoginTime > 2024-12-22T09:09:05.626+01:00  GROUP BY UserId, LoginType, AuthMethodReference, Status  ORDER BY MAX(LoginTime) LIMIT 2000
- SELECT ParentId, COUNT(SobjectType) CountObject, MAX(CreatedDate) qmField  FROM ObjectPermissions WHERE Parent.IsOwnedByProfile = FALSE AND CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY ParentId  ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT ParentId, COUNT(Field) CountField, MAX(SystemModstamp) qmField  FROM FieldPermissions WHERE Parent.IsOwnedByProfile = FALSE AND SystemModstamp > 2024-12-22T09:09:05.626+01:00  GROUP BY ParentId  ORDER BY MAX(SystemModstamp) LIMIT 2000
- SELECT PermissionSetId, COUNT(Id) CountAssignment, MAX(SystemModstamp) qmField  FROM PermissionSetAssignment WHERE PermissionSet.IsOwnedByProfile = FALSE AND Assignee.IsActive = TRUE AND SystemModstamp > 2024-12-22T09:09:05.626+01:00  GROUP BY PermissionSetId  ORDER BY MAX(SystemModstamp) LIMIT 2000
- SELECT Parent.ProfileId, COUNT(SobjectType) CountObject, MAX(CreatedDate) qmField  FROM ObjectPermissions WHERE Parent.IsOwnedByProfile = TRUE AND CreatedDate > 2024-12-22T09:09:05.626+01:00  GROUP BY Parent.ProfileId  ORDER BY MAX(CreatedDate) LIMIT 2000
- SELECT Parent.ProfileId, COUNT(Field) CountField, MAX(SystemModstamp) qmField  FROM FieldPermissions WHERE Parent.IsOwnedByProfile = TRUE AND SystemModstamp > 2024-12-22T09:09:05.626+01:00  GROUP BY Parent.ProfileId  ORDER BY MAX(SystemModstamp) LIMIT 2000
- SELECT PermissionSet.ProfileId, COUNT(Id) CountAssignment, MAX(SystemModstamp) qmField  FROM PermissionSetAssignment WHERE PermissionSet.IsOwnedByProfile = TRUE AND Assignee.IsActive = TRUE AND SystemModstamp > 2024-12-22T09:09:05.626+01:00  GROUP BY PermissionSet.ProfileId  ORDER BY MAX(SystemModstamp) LIMIT 2000

**Comment by VinceFINET** [comment]
The SOQL that does not work is this one:
```
SELECT UserId, LoginType, AuthMethodReference, Status, COUNT(Id) CntLogin, MAX(LoginTime) qmField  
FROM LoginHistory 
WHERE LoginType = 'Application' 
OR LoginType LIKE '%SSO%' 
AND LoginTime > 2024-12-22T09:09:05.626+01:00  
GROUP BY UserId, LoginType, AuthMethodReference, Status  
ORDER BY MAX(LoginTime) LIMIT 2000
```

if i add parenthesis in the good place it works back again:
```
SELECT UserId, LoginType, AuthMethodReference, Status, COUNT(Id) CntLogin, MAX(LoginTime) qmField  
FROM LoginHistory 
WHERE (LoginType = 'Application' 
OR LoginType LIKE '%SSO%') 
AND LoginTime > 2024-12-22T09:09:05.626+01:00  
GROUP BY UserId, LoginType, AuthMethodReference, Status  
ORDER BY MAX(LoginTime) LIMIT 2000
```

**Comment by VinceFINET** [comment]
i am preparing the package....

**Comment by VinceFINET** [comment]
Upgrading...

**Comment by fmimouna** [comment]
@VinceFINET it's working for me.
thanks
